# Generated by Django 3.1 on 2024-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employee_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('employees', models.ManyToManyField(blank=True, related_name='projects', to='employees.Employee')),
            ],
        ),
    ]
