# Generated by Django 5.0.6 on 2024-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('startDate', models.DateField()),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
